env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  default-case: off
  import/extensions: off
  import/no-unresolved: off
  no-await-in-loop: off
  no-plusplus: off
  no-restricted-syntax: off
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error
  no-alert: off
  max-len: off
  consistent-return: off
  react/jsx-filename-extension: off
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define': error
  object-curly-newline: off
  jsx-a11y/no-noninteractive-element-interactions: off
  jsx-a11y/no-noninteractive-element-to-interactive-role: off
  jsx-a11y/click-events-have-key-events: off
  react/no-array-index-key: off
  jsx-a11y/no-static-element-interactions: off
  jsx-a11y/media-has-caption: off
  no-param-reassign: off
