name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./docs
      - uses: actions/deploy-pages@v4.0.5
